# Generated by Django 2.2.1 on 2019-06-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('href', models.CharField(max_length=200)),
                ('tracks_href', models.CharField(max_length=200)),
            ],
        ),
    ]
