# Generated by Django 2.2.1 on 2019-06-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=500)),
                ('tracks_href', models.CharField(max_length=200)),
                ('linked', models.BooleanField(default=False)),
                ('origin_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlist.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('artist_id', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('KP', 'kept'), ('DE', 'deleted'), ('AD', 'added')], default='KP', max_length=2)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlist.Playlist')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlist.Track')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='playlist.TrackInstance', to='playlist.Track'),
        ),
    ]
